/* eslint-disable react/jsx-props-no-spreading */
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Script from 'next/script';
// eslint-disable-next-line import/no-unresolved
import { Analytics } from '@vercel/analytics/react';

import '../styles/globals.css';
import Layout from '../components/layyout/Layout';

const MyApp = ({ Component, pageProps }) => {
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    const website = fetch('https://travisg.tech');
    website.then(() => { setTimeout(() => setLoading(false), 1500); })
      .catch(() => setLoading(false));
  }, []);

  return (
    <div>
      {isLoading ? (
        <div className="md:mt-96  sm:mt-48 flex justify-center">
          {/* <div className="loader w-full h-screen" /> */}
          <div className="lds-roller"><div /><div /><div /><div /><div /><div /><div /><div /></div>
        </div>
      ) : (
        <>
          <Head>
            <title>Travis Geislinger</title>
            <meta name="description" content="Generated by create next app" key="title" />
            <link rel="icon" href="/default-monochrome-white.svg" />
            <Script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" />
          </Head>
          <Layout>
            {/* // eslint-disable-next-line react/jsx-props-no-spreading */}
            <Component {...pageProps} />
          </Layout>

          <Analytics
            beforeSend={(event) => {
              // Ignore all events that have a `/private` inside the URL
              if (event.url.includes('/private')) {
                return null;
              }
              return event;
            }}
          />
        </>
      )}
    </div>
  );
};

export default MyApp;
