/* eslint-disable react/jsx-props-no-spreading */
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Script from 'next/script';
import '../styles/globals.css';
import Layout from '../components/layyout/Layout';

const MyApp = ({ Component, pageProps }) => {
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    const website = fetch('https://travisg.tech');
    website.then(() => { })
      .catch(() => setLoading(false));
  }, []);

  return (
    <div>
      {isLoading ? (
        <div className="md:mt-96  sm:mt-48 flex justify-center">
          {/* <div className="loader w-full h-screen" /> */}
          <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_QPcsIl8rGS.json" background="transparent" speed="1" style={{ width: '300px', height: '300px' }} loop autoplay />
        </div>
      ) : (
        <>
          <Head>
            <title>Travis Geislinger</title>
            <meta name="description" content="Generated by create next app" key="title" />
            <link rel="icon" href="/default-monochrome-white.svg" />
            <Script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js" />
          </Head>
          <Layout>
            {/* // eslint-disable-next-line react/jsx-props-no-spreading */}
            <Component {...pageProps} />
          </Layout>
        </>
      )}
    </div>
  );
};

export default MyApp;
