import React from 'react';
import Head from 'next/head';
import { Hero, Testimonials } from '../components';
import { client } from '../utils/client';

const Home = ({ hero, clientsTest }) => (
  <div className="">
    <Head>
      <title>Travis Geislinger</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/default-monochrome-white.svg" />
    </Head>
    <Hero hero={hero} />
    {/* Client Testimonials */}
    <div className="flex justify-center items-center mb-5">
      <h1 className="cursor-pointer py-4 px-2 border-b-4 logoBlue font-semibold
              hover:animate-pulse navName text-6xl"
      >Testimonials
      </h1>
    </div>
    <div className="flex justify-center items-center">
      <div className="carousel carousel-center p-10 space-x-10 bg-neutral rounded-box max-w-8xl overflow-x-auto">
        {clientsTest?.map((clientTest) => <Testimonials key={clientTest._id} clients={clientTest} />)}
      </div>
    </div>
  </div>
);
export const getServerSideProps = async () => {
  // Hero Query
  const heroQuery = '*[_type == "hero"]';
  const hero = await client.fetch(heroQuery);

  // Testimonials Query
  const clientsQuery = '*[_type == "testimonials"]';
  const clientsTest = await client.fetch(clientsQuery);

  return {
    props: {
      hero,
      clientsTest,
    },
  };
};

export default Home;
