import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { Hero, Testimonials } from '../components';
import { client } from '../utils/client';
import { heroQuery, clientsQuery } from '../utils/queries';

const Home = () => {
  const [hero, setHero] = useState(null);
  const [clients, setClients] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    client.fetch(heroQuery).then((heroData) => {
      setHero(heroData);
      setLoading(false);
    });
  }, []);

  useEffect(() => {
    client.fetch(clientsQuery).then((clientData) => {
      setClients(clientData);
      setLoading(false);
    });
  }, []);

  if (loading) return 'loading';

  return (
    <div className="">
      <Head>
        <title>Travis Geislinger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/default-monochrome-white.svg" />
      </Head>
      <Hero hero={hero} />
      <Testimonials clients={clients} />
    </div>
  );
};

export default Home;
