import React from 'react';
import Head from 'next/head';
import { Carousel } from 'react-responsive-carousel';
import { Hero, Testimonials } from '../components';
import { client } from '../utils/client';
import 'react-responsive-carousel/lib/styles/carousel.min.css';

const Home = ({ hero, clientsTest }) => (
  <div className="">
    <Head>
      <title>Travis Geislinger</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/default-monochrome-white.svg" />
    </Head>
    <Hero hero={hero} />
    {/* Client Testimonials */}
    <div className="mt-10 md:mx-24 sm:mx-0 ">
      <div className="p-6 rounded-lg bg-none">
        <h1 className="navName text-black text-4xl font-bold border-green-700/100 pb-5 px-8 border-b-4">Testimonials</h1>
        <Carousel autoPlay infiniteLoop showStatus={false} showThumbs={false}>
          <div className="p-10 space-x-10 h-auto scrollbar-hide flex flex-row overflow-auto gap-2 rounded-box max-w-8xl overflow-x-auto">
            {clientsTest?.map((clientTest) => <Testimonials key={clientTest._id} clients={clientTest} />)}
          </div>
        </Carousel>
      </div>
    </div>
  </div>

);

// Data Fetching
export const getServerSideProps = async () => {
  // Hero Query
  const heroQuery = '*[_type == "hero"]';
  const hero = await client.fetch(heroQuery);

  // Testimonials Query
  const clientsQuery = '*[_type == "testimonials"]';
  const clientsTest = await client.fetch(clientsQuery);

  return {
    props: {
      hero,
      clientsTest,
    },
  };
};

export default Home;
